# default configuration
baseURL = 'http://thepink.dev/'
languageCode = "en-us"
summaryLength = "10"
theme = "kross"
title = 'The Pink Dev'

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#292729"
# contact info
#phone = "+880 2544 658 256"
email = "xani@thepink.dev"
address = "NYC, USA"
# meta description
author = "Xani"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = " &copy; 2022 [The Pink Dev](https://thepink.dev) | All Rights Reserved | Made with ♡ in NYC"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/mayvqnwg" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "40.7812"
map_longitude = "-73.9665"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/xani-dev"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/thepink.dev"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/xani-gonzalez/"